### ISSUE TITLE
Explore installing FEniCS via docker image that is based on conda

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy-FEniCS#27]
Suggested approach:

```
mkdir my_dir
cd my_dir
touch Dockerfile
touch environment.yml
docker pull continuumio/miniconda3
```

Update Dockerfile to have the following content
```
# Define base image
FROM continuumio/miniconda3
 
# Set working directory for the project
WORKDIR /app
 
# Create Conda environment from the YAML file
COPY environment.yml .
RUN conda env create -f environment.yml
```

update  environment.yml to have the following content
```
name: env
channels:
   - conda-forge
dependencies:
   - python=3.8
   - fenics
```

run the following commands (still inside my_dir)
```
docker build .
docker images
docker run --entrypoint=/bin/bash -it -p 127.0.0.1:8090:8000 --name fenics_cont -v $(pwd):/app -w /app <image_id>
```
Inside the container run:
```
conda activate env
python
```

run the following python command to make sure fenics is installed
```
import fenics
```

exit python and install cuqipy and cuqipy-fenics
```
pip install cuqipy
pip install cuqipy-fenics
```

run python
```
python
```

run the following python command to make sure cuqipy and cuqipy-fenics are installed
```
import cuqi
import cuqipy_fenics
```

**Comment by amal-ghamdi** [comment]
@babakmaboudi, just wanted to update that 
<image_id> is replaced by the image id that we see after running "docker images"

**Comment by nabriis** [comment]
The miniconda docker image works for me (at least I can import cuqipy_fenics and run the example from readme).

I think we should continue with this.

**Comment by amal-ghamdi** [comment]
We can use https://docs.docker.com to host the image.

**Comment by amal-ghamdi** [comment]
I uploaded a docker image to dockerhub:
https://hub.docker.com/r/amalalghamdi/cuqipy_fenics_image/tags

with pre installed cuqipy-fenics.

To build this image, I used the same `Dockerfile` above and slightly change `environment.yml` file

`environment.yml`:
```
name: env
channels:
   - conda-forge
dependencies:
   - python=3.8
   - fenics
   - pip
   - pip:
  # works for regular pip packages
     - cuqipy-fenics
```

**Comment by amal-ghamdi** [comment]
Note: in al least one machine, setting `environment.yml` python version to python 3.8 did not work but using python 3.10 did.

**Comment by amal-ghamdi** [comment]
# related issues #13 #22
