### ISSUE TITLE
Add StepExpansion geometry on FE meshes

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy-FEniCS#81]
Description:
-------------
Add support for step expansion in 1D and 2D for finite element FE meshes. This feature is needed to implement the [Wolfgang Bangerth elasticity benchmark](https://arxiv.org/pdf/2102.07263). The Core CUQIpy library has a StepExpansion geometry as well, but it only works for 1D structured grids. This feature, on the other hand, enables step expansion parameterization on 1D and 2D structured or unstructured meshes of generally any geometry. 

DoD:
-----
- [x] A class `StepExpantion` with a docstring example is added.
- [x] Scope: The class supports 1D and 2D cases and structured and unstructured meshes (see examples below). 
- [x] Design: The `StepExpantion` class design is consistent with the already existing `MaternKLExpansion` class in terms of keeping the interface and of StepExpansion as close as possible to `MaternKLExpansion` (the constructor parameters and the methods) as well as having a similar design in terms of building and storing basis functions. A helper private class called `_StepExpression` is added to define a FEniCS expression which to be used only by the `StepExpantion` class.
- [x] Tests are added
- [x] PR is approved

Limitation:
----------
The accuracy of the step expansion depends on the mesh resolution and whether it is structured or not. Best case scenario is when the mesh is structured and the number of elements in the x and y directions are multiples of the number of steps on the x and y directions. The examples below show steps expansion for both structured and unstructured meshes.

Additional details on design consideration:
--------------------------------------------
- Two StepExpansion classes, one in core CUQIpy and the other in CUQIpy-FEniCS:
    - The StepExpansion class in core CUQIpy works on regular 1D grids. The StepExpansion class in CUQIpy-FEniCS works with FEniCS meshes and function spaces, particularly. 
    - The latter has a dependency on FEniCS library and cannot be included in core CUQIpy without adding FEniCS as a dependency for core CUQIpy.
    - On the other hand, the core CUQIpy StepExpansion class is useful on its own for users who use CUQIpy as a stand-alone tool.
    - Using consistent naming could be suitable in this case because the two classes do the same functionality conceptually. However, below are some names of geometries in CUQIpy and the corresponding names in CUQIpy-FEniCS. In most cases we use prefix FEniCS to distinguish the two. But we did not do this for the `MaternKLExpansion` which we agreed on its naming in preparation for part II paper publication.
        - \<Core CUQIpy geometry name\> --> \<corresponding name in CUQIpy-FEniCS\>
        - Continuous1D,  Continuous2D --> FEniCSContinuous
        - MappedGeometry --> FEniCSMappedGeometry
        - KLExpansion --> MaternKLExpansion
    - The section "Error messages" below shows what happens if a user tries to create the CUQIpy StepExpansion on a mesh, and if they try to apply the CUQIPy-FEniCS StepExpansion to a grid.

Note:
-----
The corresponding PR is created by @Naokikiki and updated by @amal-ghamdi

Example of how the steps look like on a structured grid (step magnitudes are random):
![image](https://github.com/user-attachments/assets/168c5e3f-8b95-4adf-8cad-a6d435d00ede)

Example of how the steps look like on an unstructured, circular grid (step magnitudes are ordered form 0 to 15):
![image](https://github.com/user-attachments/assets/d66ea8b8-208b-47b5-a18e-0efd13282f01)

Error messages:
------------------
Initialize CUQIpy-FEniCS `StepExpansion` with a grid

```python
  G_step = StepExpansion(np.linspace(0,10),
                                num_steps_x=num_steps_x, num_steps_y=num_steps_y)
```
```
{
	"name": "NotImplementedError",
	"message": "'StepExpansion' object requires a geometry with a mesh attribute",
	"stack": "---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In [3], line 1
----> 1 G_step = StepExpansion(np.linspace(0,10),
      2                               num_steps_x=num_steps_x, num_steps_y=num_steps_y)

File ~/Documents/research_code/CUQI-DTU/forks/naoki_fork/CUQIpy-FEniCS/cuqipy_fenics/geometry.py:499, in StepExpansion.__init__(self, geometry, num_steps_x, num_steps_y)
    496     raise ValueError(\"num_steps_y must be a positive integer or None\")
    497 self._num_steps_y = num_steps_y
--> 499 self.geometry = geometry

File ~/Documents/research_code/CUQI-DTU/forks/naoki_fork/CUQIpy-FEniCS/cuqipy_fenics/geometry.py:511, in StepExpansion.geometry(self, value)
    509 # Check if the geometry has a mesh attribute
    510 if not hasattr(value, \"mesh\"):
--> 511     raise NotImplementedError(
    512         \"'StepExpansion' object requires a geometry with a mesh attribute\"
    513     )
    515 # If 1D geometry, ensure num_steps_y is None
    516 if self.physical_dim == 1 and self._num_steps_y is not None:

NotImplementedError: 'StepExpansion' object requires a geometry with a mesh attribute"
}
```

Initialize CUQIpy `StepExpansion` with a mesh
```python
G_step = StepExpansion(mesh, n_steps=5)
```
```
{
	"name": "ValueError",
	"message": "dim_grid should be int, tuple with one int element, list of numbers, 1D numpy.ndarray, or None",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [8], line 2
      1 from cuqi.geometry import StepExpansion
----> 2 G_step = StepExpansion(mesh, n_steps=5)

File ~/Documents/research_code/CUQI-DTU/CUQIpy/cuqi/geometry/_geometry.py:1162, in StepExpansion.__init__(self, grid, n_steps, fun2par_projection, **kwargs)
   1160 def __init__(self, grid, n_steps=3, fun2par_projection='mean', **kwargs):
-> 1162     super().__init__(grid, **kwargs)
   1163     self._n_steps = n_steps
   1164     self._check_grid_setup()

File ~/Documents/research_code/CUQI-DTU/CUQIpy/cuqi/geometry/_geometry.py:380, in Continuous1D.__init__(self, grid, axis_labels, **kwargs)
    379 def __init__(self, grid=None, axis_labels=None, **kwargs):
--> 380     super().__init__(grid, axis_labels, **kwargs)

File ~/Documents/research_code/CUQI-DTU/CUQIpy/cuqi/geometry/_geometry.py:308, in Continuous.__init__(self, grid, axis_labels)
    306 def __init__(self,grid=None, axis_labels=None):
    307     self.axis_labels = axis_labels
--> 308     self.grid = grid

File ~/Documents/research_code/CUQI-DTU/CUQIpy/cuqi/geometry/_geometry.py:395, in Continuous1D.grid(self, value)
    393 @Continuous.grid.setter
    394 def grid(self, value):
--> 395     self._grid = self._create_dimension(value)

File ~/Documents/research_code/CUQI-DTU/CUQIpy/cuqi/geometry/_geometry.py:325, in Continuous._create_dimension(self, dim_grid)
    323         raise ValueError(dim_grid_value_err_msg)
    324 else:
--> 325     raise ValueError(dim_grid_value_err_msg)
    326 return dim_grid.astype(float)

ValueError: dim_grid should be int, tuple with one int element, list of numbers, 1D numpy.ndarray, or None"
}
```

**Comment by amal-ghamdi** [comment]
@jakobsj , I appreciate it if you could look at the DoD, thank you.

**Comment by jakobsj** [comment]
@amal-ghamdi Thank you - this is a somewhat complex new feature and the current DoD should have a more specific details to reflect this, including its design, scope, limitations and relation to existing similar functionality StepExpansion in the core CUQIpy library. 

Also I am a bit confused when comparing issue text, DoD and PR description, where I seem to see inconsistent information.

Some points to consider and reflect in the DoD list (to keep the DoD list concise, can add more explanation in the PR description):
- Issue description mentions support for 1D and 2D, DoD mentions a single class StepExpantion, while the PR description mentions a single class StepExpansion2D (no 1D?), and also another class (non-step expansion class?) Expression2D? What exactly is to be provided? 
- The issue description mentions this is for finite element FE meshes. I understand StepExpansion for the non-FE case, but not how to interpret it in the FE case, please explain. 
- I see some possibly related text in the docstring on how the mesh should be structured and a multiple of num x y steps for accuracy, is this a recommendation, a requirement or? 
- And does it mean the mesh should consist of solely regular rectangular elements? What happens if a non-strucutured grid is attempted?
- Naming convention considerations - there is already a StepExpansion in core CUQIpy subclassed from Continuous1D. Why is a different class needed? Is it suitable to use the same class name or a different one? Suppose this would depend on how similar/different their behavior are. 

I do more or less understand the goal and contents of this, but it is important that the workflow captures the motivation and scope etc, also for future reference. Give it another go and happy to look at it again :)

**Comment by amal-ghamdi** [comment]
Hi @jakobsj, Many thanks for taking a look and for the feedback. I made another round of update. Let me know what you think when you have a chance.

**Comment by jakobsj** [comment]
THank you @amal-ghamdi refinining - that clarifies most of the points. I think the last point requires a bit of refinement:
1. Why are two separate classes needed instead of combining in one class either in CUQIpy or in CUQIpy-fenics?
2. From a user perspective, is it suitable that the two classes have the same name (to indicate that they do the same) or slightly different (to avoid confusion after import and clarify if they behave similarly but not exactly the same? What will give the best user experience with the least amount of confusion?
3. Specifically, for example, what happens/should happen if a user tries to create the CUQIpy StepExpansion on a mesh, and if they try to apply the CUQIPy-fenics stepexpansion to a non-mesh case?
4. Unrelated, please can you elaborate what is meant by this new class being consistent with the MaternKLExpansion.
Thanks!

**Comment by amal-ghamdi** [comment]
> THank you @amal-ghamdi refinining - that clarifies most of the points. I think the last point requires a bit of refinement:
> 
> 1. Why are two separate classes needed instead of combining in one class either in CUQIpy or in CUQIpy-fenics?
> 2. From a user perspective, is it suitable that the two classes have the same name (to indicate that they do the same) or slightly different (to avoid confusion after import and clarify if they behave similarly but not exactly the same? What will give the best user experience with the least amount of confusion?
> 3. Specifically, for example, what happens/should happen if a user tries to create the CUQIpy StepExpansion on a mesh, and if they try to apply the CUQIPy-fenics stepexpansion to a non-mesh case?
> 4. Unrelated, please can you elaborate what is meant by this new class being consistent with the MaternKLExpansion.
>    Thanks!

Hi @jakobsj thank you for your review and raising these considerations. I added a section "Additional details on design consideration" to add details about these points. Let me know if you have further comments.

**Comment by jakobsj** [comment]
@amal-ghamdi Many thanks for the additional details, very helpful. It sounds like it could be relevant towards naming consistency and distinguishing CUQIpy and Fenics plugin versions to rename the fenics step expansion by prepending "FEniCS" as done in most other classes available in both?

**Comment by amal-ghamdi** [comment]
> @amal-ghamdi Many thanks for the additional details, very helpful. It sounds like it could be relevant towards naming consistency and distinguishing CUQIpy and Fenics plugin versions to rename the fenics step expansion by prepending "FEniCS" as done in most other classes available in both?

This is a good point, We can talk about it. In some sense StepExpantion now is close in design to "MaternKLExpansion" and one approach is to follow the naming of "MaternKLExpansion" and not use prefix "FEniCS". We also have another related issue to refactor both #82 and we can add this naming issue to it. So that 
 we make sure both are consistent with each other and possibly consistent with other geometries.

**Comment by amal-ghamdi** [comment]
@jakobsj

**Comment by jakobsj** [comment]
@amal-ghamdi   As calling syntax and functionality is different from the existing core cuqipy StepExpansion, I think best at this point to use the "FEniCS" prefix to distinguish and make this new StepExpansion consistent with the naming used in our fenics module. Including the "FEniCS" prefix now does not prevent us from a more wide-ranging refactoring/renaming at a later time, but it does ensure more consistent naming at the point of merging ie now. While implemented based on the MaternKLExpansion, its functionality has no immediate relation to Matern so I think clearest for the user that its name does not include any "matern". So in summary, I'd say please rename with "FEniCS" prefix.

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj for your feedback. I updated the class name. It sounds like a good intermediate solution until we think about plug-in-wide renaming #66
